apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection
        image: hemanth1325/fraud-detection-app
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
spec:
  type: NodePort
  selector:
    app: fraud-detection
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30007
